services:
  frontend:
    build: ./frontend
    container_name: ft_frontend
    depends_on:
      - backend
    networks:
      - ft_network

  backend:
    build: ./backend
    container_name: ft_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - ft_network

  db:
    build: ./DataBase
    container_name: ft_db
    ports:
      - "4000:4000"
    volumes:
      - ./DataBase/data:/usr/src/app/data
    networks:
      - ft_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ft_nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ft_network


networks:
  ft_network:
    driver: bridge

