services:
  frontend:
    build: ./frontend
    container_name: ft_frontend
    depends_on:
      - backend
    networks:
      - ft_network

  backend:
    build: ./backend
    container_name: ft_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - shared_db_data:/db_data # AJOUTÉ: pour accéder à la base de données
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_started # MODIFIÉ: attendre que db ait démarré
    networks:
      - ft_network

  db:
    build: ./DataBase
    container_name: ft_db
    volumes:
      - shared_db_data:/usr/src/app # MODIFIÉ: utilise le volume nommé pour que app.js s'exécute et que database.db soit persisté et partagé
    networks:
      - ft_network

  nginx:
    build: ./nginx
    container_name: ft_nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/dist:/usr/share/nginx/html # SUPPRIMÉ: Nginx va proxy vers le service frontend
    networks:
      - ft_network


networks:
  ft_network:
    driver: bridge

volumes: # AJOUTER CETTE SECTION EN HAUT OU EN BAS DU FICHIER
  shared_db_data: