services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000"
    networks:
      - app_network
    volumes:
    - ./DataBase/data:/db_data
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

  database:
    build: ./DataBase
    container_name: sqlite-db
    volumes:
      - ./DataBase/data:/data
    networks:
      - app_network
    restart: on-failure

networks:
  app_network:
    driver: bridge