services:
  frontend:
    build: ./frontend
    container_name: ft_frontend
    networks:
      - ft_network

  backend:
    build: ./backend
    container_name: ft_backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - ft_network

  db:
    build: ./DataBase
    container_name: ft_db
    volumes:
      - ./DataBase/data:/usr/src/app/data
    networks:
      - ft_network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: ft_nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - ft_network


networks:
  ft_network:
    driver: bridge

