
services:
  frontend:
    build: ./frontend
    container_name: ft_frontend
    depends_on:
      - backend
    networks:
      - ft_network

  backend:
    build: ./backend
    container_name: ft_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - ft_network

  db:
    build: ./DataBase
    container_name: ft_db
    volumes:
      - ./database:/data
    networks:
      - ft_network

  nginx:
    build: ./nginx
    container_name: ft_nginx
    ports:
      - "80:80" # Redirige localhost:80 vers Nginx
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - ft_network

networks:
  ft_network:
    driver: bridge